baseURL = "https://arpi.io"
languageCode = "en-us"
title = "Arpi Beshlikyan"
theme = "Highlights"

[params]

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesom's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engings feel free to add a few informations.
  # This lines will be inserted as meta tags.
  name = "Arpi Beshlikyan"
  description = "an engineer with a passion for design"

  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "aybeshlikyan@g.ucla.edu"

  # If this param is set to true, every section gets an own background image (located at static/images)
  # to change the image you could use the param picture on every section.
  # If it's disabled you could change the background to overwrite the bg.jpg and overlay.png to set the background.
  backgroundpersection = false

  # hero Section
  [params.hero]
    type = "hero"
    title = "Arpi Beshlikyan"
    description = "an engineer with a passion for design"
    resumelink = "./Arpi_Beshlikyan_Resume.pdf"
    resumetext = "See my resume"
    buttontext = "About Me"

  # about section
  [[params.block]]
    id = "about"
    type = "text"
    title = "Who I Am"
    description = "I'm a 4th-year Computer Science and Engineering major at UCLA. I graduate in June 2020, and I'm currently seeking a full-time position or internship starting in the summer. I'm interested in Machine Learning and UI/UX design."
    buttontext = "next"
    # the picture is stored at static/images/


  # skill section
  [[params.block]]
    id = "skills"
    type = "list"
    title = "Stuff I do"
    description = "You can see my resume [here](./Arpi_Beshlikyan_Resume.pdf)."
    buttontext = "next"
    # the picture is stored at static/images/


    [[params.block.item]]
      icon = "fa-code"
      title = "Coding"
      link = "https://github.com/aybeshlikyan"

    [[params.block.item]]
      icon = "fa-palette"
      title = "Design"
      link = "https://vsco.co/arpibee"

    [[params.block.item]]
      icon = "fa-camera"
      title = "Photography"
      link = "https://vsco.co/arpibee"

    [[params.block.item]]
      icon = "fa-cog"
      title = "Engineering"
      link = "https://github.com/aybeshlikyan"

  # infos section
  [[params.block]]
    id = "infos"
    type = "text"
    title = "One more thing"
    description = "I want to wake up in the morning excited about the work I'm going to do that day. I want to help people. I see the impact technology can have on both individual lives and entire communities. I'm so excited to find an opportunity that will not only teach and inspire me but will also enable me to do good."
    # the picture is stored at static/images/


#  # custom section
#  [[params.block]]
#    id = "important"
#    # to make custom section copy <theme>/layouts/partials/text.html to /layouts/partials/custom.html and edit it according to your needs.
#    type = "custom"
#    title = "Don't forget"
#    description = "Curabitur massa ante, semper at massa et, semper pellentesque velit. Duis tempor est nisi, a gravida risus malesuada eget. Nunc rutrum arcu laoreet mauris sodales vehicula. Nunc iaculis felis ac dui egestas, vel ullamcorper tellus bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque lacinia sem porttitor, fringilla metus at, convallis quam. Integer convallis a justo non pellentesque."
#    # the picture is stored at static/images/
#    picture = "pic04.jpg"

  # contact form
  [[params.block]]
    id = "contact"
    type = "contact"
    title = "Get in Touch"
    picture = "pic05.jpg"

    [params.block.form]
      name = "Name"
      email = "Your Email"
      message = "Your Message"
      buttontext = "send message"

  # footer section
  # this section includes last block and social icons

  [params.footer]
    enable = true

    # social icons
    [params.footer.social_list]
      enable = true

      [[params.footer.social]]
        title = "Github"
        icon = "fa-github"
        link = "https://github.com/aybeshlikyan"

      [[params.footer.social]]
        title = "Dribbble"
        icon = "fa-dribbble"
        link = "https://dribbble.com/arpi"

      [[params.footer.social]]
        title = "LinkedIn"
        icon = "fa-linkedin"
        link = "https://linkedin.com/in/aybeshlikyan"


      [[params.footer.social]]
        title = "Instagram"
        icon = "fa-instagram"
        link = "https://instagram.com/arpibee"


    # copyright
    #[params.footer.copyright.notice]

      [[params.footer.copyright.notice]]
        text = "Copyright © 2020 by Arpi Beshlikyan "

      [[params.footer.copyright.notice]]
        text = "Design: [HTML5UP](//html5up.net)"
